//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDCDataServiceLib.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialSubType
    {
        public int MaterialSubTypeId { get; set; }
        public int MaterialId { get; set; }
        public string MaterialSubType1 { get; set; }
        public Nullable<decimal> DefaultCost { get; set; }
    }
}
