//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDCDataServiceLib.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyCompany
    {
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public int ContactNo { get; set; }
        public Nullable<int> VatTinNo { get; set; }
    }
}
