//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDCDataServiceLib.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int FermId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Email { get; set; }
        public Nullable<int> ContactNo { get; set; }
        public Nullable<bool> IsCustomer { get; set; }
        public Nullable<bool> IsEmployee { get; set; }
        public Nullable<bool> IsSupplier { get; set; }
        public Nullable<bool> IsFerm { get; set; }
    }
}
